dist: bionic
language: java

jobs:
  include:
    - stage: compile
      script: mvn package
    - stage: deploy
      script: skip
      deploy:
        provider: script
        script: mvn deploy --settings .travis.settings.xml
        cleanup: false
        skip_cleanup: true
        on:
          tags: true
    - stage: deploy
      script: skip
      deploy:
        provider: script
        script: >-
          mvn javadoc:javadoc &&
          mv target/site/apidocs $HOME &&
          cd $HOME &&
          git clone --quiet --branch=gh-pages https://${GH_TOKEN}@github.com/Renaud11232/StreamScraperReloaded.git gh-pages > /dev/null 2>&1 &&
          cd gh-pages &&
          git config user.email "travis@travis-ci.org" &&
          git config user.name "Travis CI" &&
          rm -rf * &&
          mv $HOME/apidocs/* . &&
          git add . &&
          git commit --message "Travis build : $TRAVIS_BUILD_NUMBER" &&
          git push -fq origin gh-pages > /dev/null 2>&1
        cleanup: false
        skip_cleanup: true
        on:
          tags: true
    - stage: deploy
      script: skip
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file_glob: true
        file: target/*.jar
        cleanup: false
        skip_cleanup: true
        on:
          tags: true